server:
  port: 8201
datasource:
  url: 120.76.193.248:3306/springcloud
spring:
  application:
    name: bookservice
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=UTC
    username: springcloud
    password: RAfw2FCjMcCHjjhs
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
